# Lab | Data Aggregation and Filtering

In this challenge, we will continue to work with customer data from an insurance company. We will use the dataset called marketing_customer_analysis.csv, which can be found at the following link:

https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis.csv

This dataset contains information such as customer demographics, policy details, vehicle information, and the customer's response to the last marketing campaign. Our goal is to explore and analyze this data by first performing data cleaning, formatting, and structuring.

1. Create a new DataFrame that only includes customers who:
   - have a **low total_claim_amount** (e.g., below $1,000),
   - have a response "Yes" to the last marketing campaign.

2. Using the original Dataframe, analyze:
   - the average `monthly_premium` and/or customer lifetime value by `policy_type` and `gender` for customers who responded "Yes", and
   - compare these insights to `total_claim_amount` patterns, and discuss which segments appear most profitable or low-risk for the company.

3. Analyze the total number of customers who have policies in each state, and then filter the results to only include states where there are more than 500 customers.

4. Find the maximum, minimum, and median customer lifetime value by education level and gender. Write your conclusions.

In [4]:
import pandas as pd

# Load marketing_customer_analysis
url = "https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis.csv"
df = pd.read_csv(url)

In [5]:
df.shape

(10910, 26)

In [6]:
df.head()

,Unnamed: 0,Customer,State,Customer Lifetime Value,Response,Coverage,Education,Effective To Date,EmploymentStatus,Gender,...,Number of Open Complaints,Number of Policies,Policy Type,Policy,Renew Offer Type,Sales Channel,Total Claim Amount,Vehicle Class,Vehicle Size,Vehicle Type
0,0,DK49336,Arizona,4809.216960,No,Basic,College,2/18/11,Employed,M,...,0.0,9,Corporate Auto,Corporate L3,Offer3,Agent,292.800000,Four-Door Car,Medsize,NaN
1,1,KX64629,California,2228.525238,No,Basic,College,1/18/11,Unemployed,F,...,0.0,1,Personal Auto,Personal L3,Offer4,Call Center,744.924331,Four-Door Car,Medsize,NaN
2,2,LZ68649,Washington,14947.917300,No,Basic,Bachelor,2/10/11,Employed,M,...,0.0,2,Personal Auto,Personal L3,Offer3,Call Center,480.000000,SUV,Medsize,A
3,3,XL78013,Oregon,22332.439460,Yes,Extended,College,1/11/11,Employed,M,...,0.0,2,Corporate Auto,Corporate L3,Offer2,Branch,484.013411,Four-Door Car,Medsize,A
4,4,QA50777,Oregon,9025.067525,No,Premium,Bachelor,1/17/11,Medical Leave,F,...,NaN,7,Personal Auto,Personal L2,Offer1,Branch,707.925645,Four-Door Car,Medsize,NaN

In [7]:
df.columns

Index(['Unnamed: 0', 'Customer', 'State', 'Customer Lifetime Value',
       'Response', 'Coverage', 'Education', 'Effective To Date',
       'EmploymentStatus', 'Gender', 'Income', 'Location Code',
       'Marital Status', 'Monthly Premium Auto', 'Months Since Last Claim',
       'Months Since Policy Inception', 'Number of Open Complaints',
       'Number of Policies', 'Policy Type', 'Policy', 'Renew Offer Type',
       'Sales Channel', 'Total Claim Amount', 'Vehicle Class', 'Vehicle Size',
       'Vehicle Type'],
      dtype='str')

In [8]:
filtered_df = df[
    (df["Total Claim Amount"] < 1000) & 
    (df["Response"] == 'Yes') &
    (df["Total Claim Amount"].notna())
]

In [9]:
filtered_df

,Unnamed: 0,Customer,State,Customer Lifetime Value,Response,Coverage,Education,Effective To Date,EmploymentStatus,Gender,...,Number of Open Complaints,Number of Policies,Policy Type,Policy,Renew Offer Type,Sales Channel,Total Claim Amount,Vehicle Class,Vehicle Size,Vehicle Type
3,3,XL78013,Oregon,22332.439460,Yes,Extended,College,1/11/11,Employed,M,...,0.0,2,Corporate Auto,Corporate L3,Offer2,Branch,484.013411,Four-Door Car,Medsize,A
8,8,FM55990,California,5989.773931,Yes,Premium,College,1/19/11,Employed,M,...,0.0,1,Personal Auto,Personal L1,Offer2,Branch,739.200000,Sports Car,Medsize,NaN
15,15,CW49887,California,4626.801093,Yes,Basic,Master,1/16/11,Employed,F,...,0.0,1,Special Auto,Special L1,Offer2,Branch,547.200000,SUV,Medsize,NaN
19,19,NJ54277,California,3746.751625,Yes,Extended,College,2/26/11,Employed,F,...,1.0,1,Personal Auto,Personal L2,Offer2,Call Center,19.575683,Two-Door Car,Large,A
27,27,MQ68407,Oregon,4376.363592,Yes,Premium,Bachelor,2/28/11,Employed,F,...,0.0,1,Personal Auto,Personal L3,Offer2,Agent,60.036683,Four-Door Car,Medsize,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10844,10844,FM31768,Arizona,5979.724161,Yes,Extended,High School or Below,2/7/11,Employed,F,...,0.0,3,Personal Auto,Personal L1,Offer2,Agent,547.200000,Four-Door Car,Medsize,NaN
10852,10852,KZ80424,Washington,8382.478392,Yes,Basic,Bachelor,1/27/11,Employed,M,...,0.0,2,Personal Auto,Personal L2,Offer2,Call Center,791.878042,NaN,NaN,A
10872,10872,XT67997,California,5979.724161,Yes,Extended,High School or Below,2/7/11,Employed,F,...,0.0,3,Personal Auto,Personal L3,Offer2,Agent,547.200000,Four-Door Car,Medsize,NaN
10887,10887,BY78730,Oregon,8879.790017,Yes,Basic,High School or Below,2/3/11,Employed,F,...,0.0,7,Special Auto,Special L2,Offer1,Agent,528.200860,SUV,Small,A
10897,10897,MM70762,Arizona,9075.768214,Yes,Basic,Master,1/26/11,Employed,M,...,0.0,8,Personal Auto,Personal L1,Offer1,Agent,158.077504,Sports Car,Medsize,A

In [11]:
print(f"Total filtered customers: {len(filtered_df)}")
print(filtered_df.head())
print(f"\nAvg claim amount: ${filtered_df["Total Claim Amount"].mean():.2f}")

Total filtered customers: 1399
    Unnamed: 0 Customer       State  Customer Lifetime Value Response  \
3            3  XL78013      Oregon             22332.439460      Yes
8            8  FM55990  California              5989.773931      Yes
15          15  CW49887  California              4626.801093      Yes
19          19  NJ54277  California              3746.751625      Yes
27          27  MQ68407      Oregon              4376.363592      Yes

    Coverage Education Effective To Date EmploymentStatus Gender  ...  \
3   Extended   College           1/11/11         Employed      M  ...
8    Premium   College           1/19/11         Employed      M  ...
15     Basic    Master           1/16/11         Employed      F  ...
19  Extended   College           2/26/11         Employed      F  ...
27   Premium  Bachelor           2/28/11         Employed      F  ...

    Number of Open Complaints Number of Policies     Policy Type  \
3                         0.0                  2  Corporate Auto
8                         0.0                  1   Personal Auto
15                        0.0                  1    Special Auto
19                        1.0                  1   Personal Auto
27                        0.0                  1   Personal Auto

          Policy  Renew Offer Type  Sales Channel  Total Claim Amount  \
3   Corporate L3            Offer2         Branch          484.013411
8    Personal L1            Offer2         Branch          739.200000
15    Special L1            Offer2         Branch          547.200000
19   Personal L2            Offer2    Call Center           19.575683
27   Personal L3            Offer2          Agent           60.036683

    Vehicle Class Vehicle Size Vehicle Type
3   Four-Door Car      Medsize            A
8      Sports Car      Medsize          NaN
15            SUV      Medsize          NaN
19   Two-Door Car        Large            A
27  Four-Door Car      Medsize          NaN

[5 rows x 26 columns]

Avg claim amount: $412.13

In [12]:
#2

yes_df = df[df['Response'] == 'Yes']

# Group by policy_type and gender
premium_analysis = yes_df.groupby(["Policy Type", "Gender"])["Monthly Premium Auto"].agg(
    avg_monthly_premium='mean',
    customer_count='count'
).round(2)

print(premium_analysis)

                       avg_monthly_premium  customer_count
Policy Type    Gender
Corporate Auto F                     94.30             169
               M                     92.19             154
Personal Auto  F                     99.00             540
               M                     91.09             536
Special Auto   F                     92.31              35
               M                     86.34              32

In [13]:
customer_analysis = yes_df.groupby(["Policy Type", "Gender"]).agg(
    avg_clv=("Customer Lifetime Value", 'mean'),
    avg_premium=("Monthly Premium Auto", 'mean'),
    avg_claim=("Total Claim Amount", 'mean'),
    customer_count=("Customer Lifetime Value", 'count')
).round(2)

print(customer_analysis)

                       avg_clv  avg_premium  avg_claim  customer_count
Policy Type    Gender
Corporate Auto F       7712.63        94.30     433.74             169
               M       7944.47        92.19     408.58             154
Personal Auto  F       8339.79        99.00     452.97             540
               M       7448.38        91.09     457.01             536
Special Auto   F       7691.58        92.31     453.28              35
               M       8247.09        86.34     429.53              32

In [14]:
customer_analysis['claim_to_premium_ratio'] = (
    customer_analysis['avg_claim'] / (customer_analysis['avg_premium'] * 12) #Annual premium revenue (monthly)
).round(3)

print(customer_analysis.sort_values('avg_clv', ascending=False)) #Sort by profitability (highest CLV first)

                       avg_clv  avg_premium  avg_claim  customer_count  \
Policy Type    Gender
Personal Auto  F       8339.79        99.00     452.97             540
Special Auto   M       8247.09        86.34     429.53              32
Corporate Auto M       7944.47        92.19     408.58             154
               F       7712.63        94.30     433.74             169
Special Auto   F       7691.58        92.31     453.28              35
Personal Auto  M       7448.38        91.09     457.01             536

                       claim_to_premium_ratio
Policy Type    Gender
Personal Auto  F                        0.381
Special Auto   M                        0.415
Corporate Auto M                        0.369
               F                        0.383
Special Auto   F                        0.409
Personal Auto  M                        0.418

In [ ]:
#Corporate Auto is the most profitable segment with the lowest claim cost relative to premium, driven by men (0.369)
#Women tend to have better ratios in Personal Auto than men (0.381 - 0.418)

In [10]:
#Group by state and count customers

state_counts = df.groupby('State')['Customer'].count().reset_index()
state_counts.columns = ['State', 'Customer_Count']


filtered_states = state_counts[state_counts['Customer_Count'] > 500].copy() #States with more than 500 customers

In [11]:
print(f"\nTotal states meeting criteria: {len(filtered_states)}")
print(f"\nFiltered DataFrame:\n{filtered_states.sort_values('Customer_Count', ascending=False)}")
print(f"\nTotal customers in filtered states: {filtered_states['Customer_Count'].sum()}")

Total states meeting criteria: 5

Filtered DataFrame:
        State  Customer_Count
1  California            3552
3      Oregon            2909
0     Arizona            1937
2      Nevada             993
4  Washington             888

Total customers in filtered states: 10279

In [16]:
#Statistics by Gender and Education Level

clv_df = df[df['Customer Lifetime Value'].notna()].copy()

In [17]:
#Groupby Education and Level

clv_by_segment = clv_df.groupby(['Education', 'Gender'])['Customer Lifetime Value'].agg(
    max_clv='max',
    min_clv='min',
    median_clv='median',
    customer_count='count',
    mean_clv='mean'
).round(2)

In [18]:
# Sort by median CLV (descending)
clv_by_segment = clv_by_segment.sort_values('median_clv', ascending=False)

In [19]:
print(f"\n{clv_by_segment}\n")

                              max_clv  min_clv  median_clv  customer_count  \
Education            Gender
High School or Below M       83325.38  1940.98     6286.73            1556
                     F       55277.45  2144.92     6039.55            1590
College              M       61134.68  1918.12     6005.85            1596
Master               F       51016.07  2417.78     5729.86             475
Bachelor             F       73225.96  1904.00     5640.51            1700
College              F       61850.19  1898.68     5623.61            1608
Master               M       50568.26  2272.31     5579.10             412
Doctor               M       32677.34  2267.60     5577.67             201
Bachelor             M       67907.27  1898.01     5548.03            1572
Doctor               F       44856.11  2395.57     5332.46             200

                             mean_clv
Education            Gender
High School or Below M        8149.69
                     F        8675.22
College              M        8052.46
Master               F        8157.05
Bachelor             F        7874.27
College              F        7748.82
Master               M        8168.83
Doctor               M        7415.33
Bachelor             M        7703.60
Doctor               F        7328.51

## Bonus

5. The marketing team wants to analyze the number of policies sold by state and month. Present the data in a table where the months are arranged as columns and the states are arranged as rows.

6.  Display a new DataFrame that contains the number of policies sold by month, by state, for the top 3 states with the highest number of policies sold.

*Hint:*
- *To accomplish this, you will first need to group the data by state and month, then count the number of policies sold for each group. Afterwards, you will need to sort the data by the count of policies sold in descending order.*
- *Next, you will select the top 3 states with the highest number of policies sold.*
- *Finally, you will create a new DataFrame that contains the number of policies sold by month for each of the top 3 states.*

7. The marketing team wants to analyze the effect of different marketing channels on the customer response rate.

Hint: You can use melt to unpivot the data and create a table that shows the customer response rate (those who responded "Yes") by marketing channel.

External Resources for Data Filtering: https://towardsdatascience.com/filtering-data-frames-in-pandas-b570b1f834b9